// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/grpc/connectionpool/connection_pool.proto

package connectionpool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Dsn           string                 `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"` // Data Source Name for PostgreSQL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConnectionRequest) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConnectionRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRelease) Reset() {
	*x = ConnectionRelease{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRelease) ProtoMessage() {}

func (x *ConnectionRelease) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRelease.ProtoReflect.Descriptor instead.
func (*ConnectionRelease) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionRelease) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{4}
}

func (x *StatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type StatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections int32                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	IdleConnections   int32                  `protobuf:"varint,2,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	TotalConnections  int32                  `protobuf:"varint,3,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_connectionpool_connection_pool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *StatsResponse) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *StatsResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *StatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_connectionpool_connection_pool_proto protoreflect.FileDescriptor

const file_internal_grpc_connectionpool_connection_pool_proto_rawDesc = "" +
	"\n" +
	"2internal/grpc/connectionpool/connection_pool.proto\x12\x0econnectionpool\"B\n" +
	"\x11ConnectionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\"O\n" +
	"\x12ConnectionResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x11ConnectionRelease\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"A\n" +
	"\x0fReleaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\fStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xac\x01\n" +
	"\rStatsResponse\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10idle_connections\x18\x02 \x01(\x05R\x0fidleConnections\x12+\n" +
	"\x11total_connections\x18\x03 \x01(\x05R\x10totalConnections\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x9b\x02\n" +
	"\x15ConnectionPoolService\x12X\n" +
	"\rGetConnection\x12!.connectionpool.ConnectionRequest\x1a\".connectionpool.ConnectionResponse\"\x00\x12Y\n" +
	"\x11ReleaseConnection\x12!.connectionpool.ConnectionRelease\x1a\x1f.connectionpool.ReleaseResponse\"\x00\x12M\n" +
	"\fGetPoolStats\x12\x1c.connectionpool.StatsRequest\x1a\x1d.connectionpool.StatsResponse\"\x00BQZOgithub.com/teresa-solution/connection-pool-manager/internal/grpc/connectionpoolb\x06proto3"

var (
	file_internal_grpc_connectionpool_connection_pool_proto_rawDescOnce sync.Once
	file_internal_grpc_connectionpool_connection_pool_proto_rawDescData []byte
)

func file_internal_grpc_connectionpool_connection_pool_proto_rawDescGZIP() []byte {
	file_internal_grpc_connectionpool_connection_pool_proto_rawDescOnce.Do(func() {
		file_internal_grpc_connectionpool_connection_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_connectionpool_connection_pool_proto_rawDesc), len(file_internal_grpc_connectionpool_connection_pool_proto_rawDesc)))
	})
	return file_internal_grpc_connectionpool_connection_pool_proto_rawDescData
}

var file_internal_grpc_connectionpool_connection_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_grpc_connectionpool_connection_pool_proto_goTypes = []any{
	(*ConnectionRequest)(nil),  // 0: connectionpool.ConnectionRequest
	(*ConnectionResponse)(nil), // 1: connectionpool.ConnectionResponse
	(*ConnectionRelease)(nil),  // 2: connectionpool.ConnectionRelease
	(*ReleaseResponse)(nil),    // 3: connectionpool.ReleaseResponse
	(*StatsRequest)(nil),       // 4: connectionpool.StatsRequest
	(*StatsResponse)(nil),      // 5: connectionpool.StatsResponse
}
var file_internal_grpc_connectionpool_connection_pool_proto_depIdxs = []int32{
	0, // 0: connectionpool.ConnectionPoolService.GetConnection:input_type -> connectionpool.ConnectionRequest
	2, // 1: connectionpool.ConnectionPoolService.ReleaseConnection:input_type -> connectionpool.ConnectionRelease
	4, // 2: connectionpool.ConnectionPoolService.GetPoolStats:input_type -> connectionpool.StatsRequest
	1, // 3: connectionpool.ConnectionPoolService.GetConnection:output_type -> connectionpool.ConnectionResponse
	3, // 4: connectionpool.ConnectionPoolService.ReleaseConnection:output_type -> connectionpool.ReleaseResponse
	5, // 5: connectionpool.ConnectionPoolService.GetPoolStats:output_type -> connectionpool.StatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_connectionpool_connection_pool_proto_init() }
func file_internal_grpc_connectionpool_connection_pool_proto_init() {
	if File_internal_grpc_connectionpool_connection_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_connectionpool_connection_pool_proto_rawDesc), len(file_internal_grpc_connectionpool_connection_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_connectionpool_connection_pool_proto_goTypes,
		DependencyIndexes: file_internal_grpc_connectionpool_connection_pool_proto_depIdxs,
		MessageInfos:      file_internal_grpc_connectionpool_connection_pool_proto_msgTypes,
	}.Build()
	File_internal_grpc_connectionpool_connection_pool_proto = out.File
	file_internal_grpc_connectionpool_connection_pool_proto_goTypes = nil
	file_internal_grpc_connectionpool_connection_pool_proto_depIdxs = nil
}
